### ISSUE TITLE
Enable automatic scrolling for syllable text box

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1001]
It would be very useful if clicking on a syllable or bounding box made the "Syllable on this page" box scroll to make that syllable visible. At the moment, when I click on a syllable that isn't visible in the "Syllables on this page" box, nothing happens and I have to scroll myself to see which syllable I selected. Demo:

https://user-images.githubusercontent.com/83373378/233996688-fc0a8f53-1d85-4583-98d0-a28e96e71e60.mov

This doesn't hamper correction, but it would be more convenient if the scrolling happened automatically!

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I added hotkey `Shift + T` for auto scrolling to highlighted syl text. Please let me know how you feel about it!

**Comment by JoyfulGen** [comment]
@yinanazhou it works very well! I'm wondering though, would it be possible to make it fully automatic? Like if I select a syllable whose text nugget isn't on screen, the text box automatically scrolls to it without me having to do anything. I'm asking just in case it's an easy tweak; if not, the hotkey will be very useful!

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, we can definitely do that. My concern is that if we make it fully automatic, the user might need to scroll back for the display/insert/edit actions all the time. Please let me know your opinion about this.

**Comment by JoyfulGen** [comment]
@yinanazhou I hear you! That's a really good point, and I see how my idea isn't practical. What if the automatic scrolling happened only when the user used the left/right arrow keys to navigate between bounding boxes? As far as I can imagine, that function is really only useful when the user is correcting nuggets of text, in which case they want the text to be visible, even if the display/insert/edit actions aren't.

For additional clarity, these are the steps that would trigger the automatic scrolling:
1. Select a bounding box;
2. Use an arrow key to navigate to a neighbouring bounding box.

Does that make sense? Maybe it's too finicky, but if the fix is relatively easy I would really love to try it out.

**Comment by yinanazhou** [comment]
Good point! Coming up!

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've pushed the changes.

**Comment by JoyfulGen** [comment]
@yinanazhou that is very satisfying!! It all seems to work very well, and I think it'll be very useful. Closing issue now.
