### ISSUE TITLE
DivaView not showing manuscripts

### ISSUE THREAD

**Issue by yinanazhou** [DDMAL/Neon2#1002]
We cannot open the Salzinnes manuscript in Neon now. Something in DivaView is not working.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/74484576/235513884-5dbb6a1f-ab6a-42c8-b30c-05695bed519b.png">

**Comment by yinanazhou** [comment]
Hi @annamorphism and @JoyfulGen, do you remember the last time Neon was working for manuscripts?

**Comment by annamorphism** [comment]
Honestly, no. I don't know if the demo manuscript was taken into account at all in last summer's work...

**Comment by JoyfulGen** [comment]
Agree with Anna, I've never worked with a manuscript at all!

**Comment by yinanazhou** [comment]
Closing as it has been fixed in PR #1017.
