### ISSUE TITLE
Feature request: folder level in file upload page

### ISSUE THREAD

**Issue by yinanazhou** [DDMAL/Neon2#1004]
In the uploaded documents page, it would be helpful if we add a folder level, so that it would be easier for users to retrieve files when they've uploaded lots of files. A searching/filter/label feature will also help.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/74484576/235942235-35dc62d4-c6ce-4bdd-bda0-767416a6db48.png">

**Comment by chetbae** [comment]
- [ ] File system implementation
- [ ] Navbar clickable (max)
- [ ] Fix upload documents (max)
- [ ] Create add folder functionality (max)
- [ ] Drag-and-drop moving folders/files functionality (david)
- [ ] Fix delete warning message
- [ ] UI styling (david)
