### ISSUE TITLE
Rodan-Neon is not rendering images

### ISSUE THREAD

**Issue by martha-thomae** [DDMAL/Neon2#1010]
We have an issue in Rodan-Neon, where the MEI is rendered, but the image never shows up.

Could you, @yinanazhou and @softcat477, take a look at it?

Thank you!

**Comment by softcat477** [comment]
it's showing on my end
![Screen Shot 2023-05-09 at 4 43 02 PM](https://github.com/DDMAL/Neon/assets/25975988/3520cba7-06e1-4b2d-9a97-04f863187c37)

**Comment by martha-thomae** [comment]
And I couldn't reproduce the issue today. So, I am closing it for now.
