### ISSUE TITLE
Staff resizing features misbehaving half of the time

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1011]
**Expected behaviour**

When selecting a staff, that staff becomes highlighted in red and little blue circles and diamonds appear around it. The circles allow the user to change the height or width of the staff, and the diamonds allow the user to change the tilt of the staff up or down. Clicking and dragging anywhere on the staff itself allows the user to move the entire staff and everything on it.

**Current behaviour**

At the moment, the blue circles and diamonds malfunction every other time I use them. For example:
1. Click and drag the diamond to change the tilt of the staff - this works as expected.
2. Click and drag the diamond again - now, rather than change the tilt, the entire staff moves.
3. Click and drag the diamond again - works as expected again.
4. And so on.

The same thing applies to the blue circles. Here's a demo:

https://github.com/DDMAL/Neon/assets/83373378/267c934b-69b2-49ca-b92f-60acf5379071

This doesn't completely halt correction, but it's still slowing me down somewhat.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've already pushed the change for this issue.

**Comment by JoyfulGen** [comment]
Hi @yinanazhou, I've just tested it and it still seems to be happening. I've tried both with an old file and a newly uploaded file and the phenomenon is the same.

**Comment by yinanazhou** [comment]
> Hi @yinanazhou, I've just tested it and it still seems to be happening. I've tried both with an old file and a newly uploaded file and the phenomenon is the same.

@JoyfulGen Could you please try to clean cache?

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've pushed the changes. Please let me know if it works. Thanks!

**Comment by JoyfulGen** [comment]
It works perfectly, thank you! Closing issue now.
