### ISSUE TITLE
If a syllable doesn't have text, its bounding box is invisible

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1013]
This appears to be a resurrection of https://github.com/DDMAL/Neon/issues/760.

Normally, all bounding boxes are visible all the time, regardless of whether their syllable nugget has text or not. However, between yesterday (May 22) around 11:00 Mtl time and today (May 23) 8:00 Mtl time, bounding boxes are sometimes invisible if no text has been input for their syllable. The following actions makes text-less bounding boxes disappear:

- Open a new folio, make any change, save that change, and reload the page;
- In any folio, erase the text for a bounding box, save that change, and reload the page.

Demo:

https://github.com/DDMAL/Neon/assets/83373378/38bcc28a-42a5-480a-ade5-fbccecdb25df

Unlike with issue 760, grouping a syllable with bounding box with a syllable without bounding box doesn't make the bounding box disappear.

Currently there's an easy workaround: as soon as text is input, its invisible bounding box appears. However, there being bounding boxes missing means that the user can't use keyboard shortcuts to input text, and that makes this particular user quite sad.

**Comment by yinanazhou** [comment]
So sorry about this! I forgot to move the empty syl handling to the test Neon. This should be fixed now.

**Comment by JoyfulGen** [comment]
Fixed, thank you! Closing issue now.
