### ISSUE TITLE
Oblique ligatures are rendered with punctums

### ISSUE THREAD

**Issue by noahbaxter** [DDMAL/Neon2#102]
Inside a neume tag, when 2 adjacent neume components have their ligature tags set to True (representing an oblique ligature), they are rendered as a punctum followed by a ligature. It is expected that only the ligature would be rendered.

![screen shot 2018-07-10 at 3 59 23 pm](https://user-images.githubusercontent.com/18178881/42534289-5d5e7ae2-845a-11e8-95b7-805915b7aa61.png)

**Comment by JRegimbal** [comment]
Seems to be something weird in the js version. On the command line with the same files it will render correctly, but in javascript the glyph code gets changed to 0xE990 (punctum) and as of right now I have no idea why or where.

**Comment by JRegimbal** [comment]
Actually this definitely is weird but it *does* give the user something easy to drag to adjust the oblique ligature.

**Comment by noahbaxter** [comment]
Turns out this was an error on my part. The first nc was being written with 'ligatured' as opposed to 'ligature', causing verovio to render it as a neume instead. This has been correct in the JSOMR to MEI job.
