### ISSUE TITLE
Buttons for making pairs are really big on firefox

### ISSUE THREAD

**Issue by MrMondrian** [DDMAL/Neon2#1025]
When making a pair on neon in firefox it looks like this. Nothing weird or unique was done to create this behaviour. @yinanazhou 
![Screenshot from 2023-06-14 16-44-38](https://github.com/DDMAL/Neon/assets/57821698/4a876eb8-a8ab-4078-922d-cf0776d60ee0)

**Comment by yinanazhou** [comment]
This issue is fixed in the latest commit. Closing now.
