### ISSUE TITLE
Fix Neon UI for Tablet and Phone Screens

### ISSUE THREAD

**Issue by cadagong** [DDMAL/Neon2#1030]
The UI of the content of the pancake menu has some issues with it, especially on mobile devices (width of under 900px).

**Comment by cadagong** [comment]
On tablet, the content is not perfectly aligned, and also there is some content at the bottom that can't be scrolled to (the rest of the "Help" menu as well as the feedback form link):
<img width="917" alt="Screen Shot 2023-06-20 at 9 19 37 AM" src="https://github.com/DDMAL/Neon/assets/40658078/592bad64-3c5b-4d43-b25c-2cbd170fc83f">

**Comment by cadagong** [comment]
And on mobile devices, it simply doesn't display the content properly at all:
<img width="655" alt="Screen Shot 2023-06-20 at 9 21 26 AM" src="https://github.com/DDMAL/Neon/assets/40658078/0a82f2df-602f-4a78-85e7-ae0eda87a42d">

**Comment by yinanazhou** [comment]
Closed in PR #1032
