### ISSUE TITLE
Multiple columns and multiple pages

### ISSUE THREAD

**Issue by yinanazhou** [DDMAL/Neon2#1037]
Neon should be able deal with multiple columns per page, and multiple pages per image. Reference: https://github.com/DDMAL/Rodan/issues/828

**Comment by yinanazhou** [comment]
To wrap up our meeting with @martha-thomae:
- [ ] Files should always have a `<pb>` element at the beginning of `<layer>` children, with `@facs` attribute pointing to the `@xml:id` value of the `<surface>` element.
- [ ] `<score>` should have a child `<colLayout>`, with `@cols` attribute equals to the total number of columns.
- [ ] Columns are indicated by the `<cb>` element, with `@n` attribute to the number of the column.
- [ ] `<sb>` elements should have `@n` attribute indicates the number of the staff.

**Comment by martha-thomae** [comment]
Everything is correct, just one small adjustment:

> `<score>` should have a child `<colLayout>`, with `@cols` attribute equals to the total number of columns.

This is true only when there are columns in the image (otherwise, there should be no `<colLayout>` and no `<cb>` elements).

Thanks for the summary, Yinan!

**Comment by yinanazhou** [comment]
To wrap up discussion with Laurent, Juliette, and Anna:

- [x] no need to modify verovio so far but need to test if verovio will preserve the attribute it does not support
- [x] convert `cb` information to an attribute called `data_neon_column` in `staff` inside neon to preserve column information while loading MEI files
- [x] create a `cb` element when hit a new `data_neon_column` value when exporting MEI files
- [x] show column information in `Element Info` in the format of `column 1`
- [x] calculate zones for cb
- [x] add `highlight by column` option
- [ ] add `select by column` option
- [x] remove `data_neon_column` for MEI validation
- [x] modify column info when select staffs
- [x] for newly inserted staff, automatically assign a column, and give the user option to modify column information

As for `pb`, verovio does not currently support reading `pb`. Neon will remove `pb` when sending file to verovio.

We will focus on the case of one page with multiple columns for now.

Please let me know if I left something @annamorphism

**Comment by annamorphism** [comment]
I think this summarizes the discussion pretty well! It sounds like in the long run something similar would have to happen for pb as for cb, but it can be dealt with separately.

**Comment by yinanazhou** [comment]
Hi @annamorphism and @JoyfulGen, I've pushed the changes for multicolumn support. I'm closing this issue. If you find anything unexpected, please create a new issue. Thanks!
