### ISSUE TITLE
Refactor Ungroup action in verovio

### ISSUE THREAD

**Issue by yinanazhou** [DDMAL/Neon2#1055]
- [x] Ungroup creates a big overlap in bbox 
Before ungroup:
![image](https://github.com/DDMAL/Neon/assets/74484576/cabc7041-3d52-4eaf-9ede-84e010a80422)
After ungroup:
![image](https://github.com/DDMAL/Neon/assets/74484576/2408bffb-2aa7-45f8-94f4-d1ab54b2f809)
The bbox of the first resulting syllable is too big and creates a big overlap.
- [x] Ungroup misbehave when syllable starts with layer element(s)
- [x] Y position of resulting bboxes not consistent

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've made some changes to the ungroup action. Please let me know here if there's anything not functioning well.

**Comment by JoyfulGen** [comment]
@yinanazhou this is very useful! I've encountered no problems so far, and it's made my life easier. You can close the issue as far as I'm concerned!

**Comment by yinanazhou** [comment]
Found another possible improvement: original bbox adjustment does not always work.
