### ISSUE TITLE
Two obliques in a row within one neume misbehave if any action is performed on their staff

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1058]
If a neume is created that contains two obliques one after the other, both these obliques stop looking like obliques as soon as any action (insert, delete, move, group) is made on any element on that staff. Demo:

https://github.com/DDMAL/Neon/assets/83373378/7267ffe9-4c45-4173-bce7-4dc3629f701e

Steps:
1. Create a double oblique neume (the interval of the obliques and the presence or not of other neume components in the neume don't seem to change anything);
2. Do another thing on that staff;
3. Observe the obliques lose all structural integrity.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I cannot reproduce this issue. Could you please provide the files?

**Comment by JoyfulGen** [comment]
@yinanazhou that's strange! I've tried again on multiple files and it happens every time, both with nc's I input and nc's already on the page. Here's an MEI example for 195v, where the double oblique is the second neume on the first staff, syllable "hello":

Before doing anything else on the staff (obliques look normal): [195v double oblique before.mei.zip](https://github.com/DDMAL/Neon/files/12157689/195v.double.oblique.before.mei.zip)
After doing something else on the staff (obliques look not normal): [195v double oblique after.mei.zip](https://github.com/DDMAL/Neon/files/12157690/195v.double.oblique.after.mei.zip)

And the image

![Einsiedeln__Stiftsbibliothek__Codex_611_195v](https://github.com/DDMAL/Neon/assets/83373378/b07bf802-e715-48c7-a038-625c45b00259)

**Comment by yinanazhou** [comment]
Thanks @JoyfulGen. I can reproduce the issue now. I miss the point that the two obliques have to be in one neume😅

**Comment by yinanazhou** [comment]
Hi @JoyfulGen I forgot to update here, but the changes has been pushed.

**Comment by JoyfulGen** [comment]
Indeed they have! Closing issue now.
