### ISSUE TITLE
Opacity of new bbox is not the same with the old ones

### ISSUE THREAD

**Issue by yinanazhou** [DDMAL/Neon2#1067]
https://github.com/DDMAL/Neon/assets/74484576/2b02925e-076a-407e-8f8f-471d92985121

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've pushed the changes. Please let me know how it works! Thanks!

**Comment by JoyfulGen** [comment]
@yinanazhou looks all normal now, thank you! You can close the issue as far as I'm concerned!
