### ISSUE TITLE
Feature request: tab key to go to the next bbox

### ISSUE THREAD

**Issue by yinanazhou** [DDMAL/Neon2#1079]

**Comment by yinanazhou** [comment]
Hi @JoyfulGen I've pushed the changes for `tab` and `shift + tab` hot key.

**Comment by JoyfulGen** [comment]
@yinanazhou this is great!! I will achieve such SPEED.

There's a little bug with the scrolling however. If I select a bbox and press the `tab` key, it goes to the next bbox and the highlight jumps to the next syllable in the "Syllables on this page" box. Totally great. However, if I keep pressing `tab`, after the third bbox the right-side display jumps to the top and stays there. The selection still moves from bbox to bbox, but I can't see the syllables anymore, and other parts of the page start getting selected. Demo:

https://github.com/DDMAL/Neon/assets/83373378/99f5d3b6-05c9-4870-b0c6-163887614b7b

Would it be possible to enable an automatic scroll to the bottom of the "Syllables on this page" box, like you did for the arrow keys?

**Comment by yinanazhou** [comment]
Hi @JoyfulGen I've pushed the changes

**Comment by JoyfulGen** [comment]
@yinanazhou fixed, thank you!! Closing issue again.
