### ISSUE TITLE
Site UI: double-click button vs single-click

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/Neon2#1083]
I haven't been on the site in a while, but today I noticed that various buttons operate differently. For example:

-"Get started" is a single click, highlights on hover; so is the Back button
-"Samples" is a double click, does not highlight on hover (cursor shape changes); same for all the samples themselves.
-The "open" icon doesn't highlight, is also a single click--if you have already selected a file; but since the file you've selected isn't highlighted, it's hard to tell what you are opening. 

I found it unexpected to double-click the sample files, and I thought they simply were not loading at first.

**Comment by yinanazhou** [comment]
Hi, in the latest changes we pushed, the folder/file selected will have a highlighted edge. Does it resolve this issue?

**Comment by yinanazhou** [comment]
Hi @annamorphism can I get an update about this issue?

**Comment by annamorphism** [comment]
This is different (and improved) from August, and the highlighting is a big help.  I now know to double-click on the Samples folder (which is I suppose not that different from opening a folder in Finder) but the existence of issue #1124 does suggest this is somehow not intuitive. I'm not sure what would improve it, though, so maybe this issue should be closed until further notice.

**Comment by fujinaga** [comment]
Yes, this can be closed for now.

On Nov 7, 2023, at 23:23, Anna ***@***.***> wrote:

﻿

This is different (and improved) from August, and the highlighting is a big help. I now know to double-click on the Samples folder (which is I suppose not that different from opening a folder in Finder) but the existence of issue #1124<https://github.com/DDMAL/Neon/issues/1124> does suggest this is somehow not intuitive. I'm not sure what would improve it, though, so maybe this issue should be closed until further notice.
