### ISSUE TITLE
Tab name and MEI file name don't reflect renaming of folio in Neon

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1084]
Thanks to the new excellent UI improvements, I can now rename a folio in Neon. However, once I open that file, neither the tab nor the MEI file name have changed, which is off-putting. It's also confusing if I've specifically changed the file name to differentiate it from another identical one, as is the case in the example below:

https://github.com/DDMAL/Neon/assets/83373378/b8f7fe00-e784-4a14-b1a5-e3c82bda92bd

**Comment by annamorphism** [comment]
wait... @JoyfulGen  how come you can rename files and I can't??? I was just opening an issue about this but maybe I am insane.

**Comment by chetbae** [comment]
The previous renaming function is accessed by pressing Enter while the tile is selected, or right-clicking and choosing the rename option @annamorphism !
But the newest update prompts a window, whenever it moves to prod

**Comment by annamorphism** [comment]
@chetbae oooohh! The Enter key was not on my radar, very nice!
