### ISSUE TITLE
Return of toggle insanity related to partially toggled syllables - steps below

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1085]
Disclaimer: I'm 95% sure that once https://github.com/DDMAL/Neon/issues/783#issuecomment-1672878867 is fixed, this one will be as well. But I thought I'd record what I found just in case.

**Setting the scene** -- The starting situation is very specific, so I prepared an MEI file to make reproducing the steps easier. 
[CH-E_611_130r_toggle_demo.mei.zip](https://github.com/DDMAL/Neon/files/12311526/CH-E_611_130r_toggle_demo.mei.zip)
For the record, this is what I did:
1. Split the first staff in two;
2. Merge the two last neumes of the first created staff into one syllable;
3. Toggle-link that syllable with the first one on the staff next to it;
4. Take the second neume of the first syllable and drag it to _after_ the second syllable;
5. Merge the staves back together again.
6. The result is a single staff with a "toggle sandwich" in the middle of it. The two pale blue friends (downwards liquescent and clivis) in the middle of the staff are one syllable, and that syllable is toggled to the green friend (podatus) in the middle.

**To begin**
1. Add a punctum next to the downwards liquescent and group neumes and neume components. That neume becomes its own syllable, the other two syllables remain toggled. 

**Strange Behaviour Number One**
1. From there, select all three syllables (pale blue, green, and yellow) and merge them;
2. Nothing seems to happen.
3. Now delete the first neume;
4. The remaining two neumes will automatically become a single syllable. Ain't that wild.

**Strange Behaviour Number Two**
1. Undo the step from Strange Behaviour Number One.
2. Select all three syllables and delete them. It works! Everything is as normal. 
3. Undo that.
4. Now select all three syllables and merge them - nothing seems to happen.
5. Select all three syllables again and delete them again - this time, nothing seems to happen.
6. Now select the second syllable and click on "Toggle linked syllables."
7. The first syllable disappears and the remaining two automatically become a single syllable. Also wild.

There are probably other strange things that can happen, but these are the two that I managed to reproduce systematically. 

As I mentioned above, I'm quite sure that these are a direct consequence of the syllables remaining partially toggled. So probably when that's fixed, these behaviours will stop happening.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've pushed the changes.

**Comment by JoyfulGen** [comment]
Fixed! The above series of actions don't provoke bugs anymore. Closing issue.
