### ISSUE TITLE
Sequence involving divLine in a syllable results in major bug

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1087]
There are two sequences:

**The First**
1. In any folio, find or create a syllable with two neumes.
2. Add a divisio between those two neumes and insert it into the syllable.
3. Delete the second neume.
4. Select the syllable (which now consists of the first neume and the divisio) and ungroup it. Nothing will visibly happen, but there are two consequences:
- Nothing on the page can be deleted.
- If you move pitched elements around, they stay exactly where you put them, instead of snapping to the nearest line or space as they usually do.

DEMO

https://github.com/DDMAL/Neon/assets/83373378/018e2630-bdf9-45e7-af7c-f0a7e1c30861

**The Second**
1. For this one, the syllable with the divisio in it has to already exist in the straight-outta-OMR file (a file with divisios in syllables is supplied below)
2. Again, delete the second neume of the syllable.
3. Select the syllable and ungroup it once. Again, nothing visibly happens, but the result is slightly different: if you select the syllable and delete it, the neume disappears, but the divisio remains.
4. Now if you undo that and ungroup the syllable twice in a row, the result will be the same as in the first sequence.

DEMO

https://github.com/DDMAL/Neon/assets/83373378/fef8667c-ceb5-42e1-ae6f-0b41084fde74

An MEI file with divisios in syllables (it looks a bit bad because the page glyphs are pretty faded, but it does the trick): 
[183v.mei.zip](https://github.com/DDMAL/Neon/files/12333236/183v.mei.zip)

**Comment by yinanazhou** [comment]
Hi @JoyfulGen I've pushed the changes! It turned out be caused by the lack of one line of code😅

**Comment by JoyfulGen** [comment]
@yinanazhou it's fixed, thank you!! Everything works just great :) Closing issue now.
