### ISSUE TITLE
Discussion and request: if a syllable begins or ends with a divisio, automatically remove the divisio from the syllable

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1088]
This wasn't relevant until now, because divisios weren't being inserted into syllables before the file got to Neon. But now they are! So here's the situation:

If, in the straight-outta-OMR file, there's a syllable composed of more than one neume and at least one divisio, it's possible to interact with that syllable such that you end up with a syllable that begins or ends with a divisio. It has been previously agreed that a divisio should be inserted into a syllable only if it's between neumes of that syllable. Also, at the moment situations like these are creating chaos (https://github.com/DDMAL/Neon/issues/1087). 

My suggestion is that if you interact with a syllable and the result is that it begins or ends with a diviso, that divisio is automatically removed from the syllable. The interactions I can think of where that would happen are:
- Deleting one of the outer neumes of the syllable.
- Editing one of the outer neumes of the syllable, which makes that neume automatically ungroup from the first syllable and become its own syllable.

@yinanazhou @annamorphism what do you think? Does this make sense within chant logic, and is it possible?

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I remember from the discussion last year, this kind of change should be made in the MEI encoding job. For automatic removing after actions, I think it's better to give the user the option. I will investigate issue #1087 further and let you know.

**Comment by JoyfulGen** [comment]
@yinanazhou I don't see how this change can be made in MEI_encoding, because in this case it's the user's interaction that makes the divisio be wrongly inserted. So far, MEI encoding is reliably inserting divisios only when they have neumes surrounding them. So from what I can tell, this specific issue occurs in Neon, not before. Am I understanding this right?

I understand that automatic actions aren't great though, so that's no problem!

**Comment by yinanazhou** [comment]
@JoyfulGen yes, you are correct. I misunderstood the issue. I checked issue #1087, and it seems to be related to the group and ungroup action. I will fix it first, and see if there's need for automatic removing then. But in general, we don't want anything automatically happen without the permission of the user.

**Comment by yinanazhou** [comment]
For now you can use the `Move outside syllable` option to move the divLine outside. Sorry for the inconvenience.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen it's been a while since the last update about this issue. Can I get an update about how you feel about it now?

**Comment by JoyfulGen** [comment]
@yinanazhou I think that if https://github.com/DDMAL/Neon/issues/1115#issuecomment-1802779851 becomes official, this issue won't happen very much anymore, because it won't really be possible to interact with a neume without interacting with the syllable. Can we wait and see what happens with 1115 first?

**Comment by JoyfulGen** [comment]
https://github.com/DDMAL/Neon/issues/1115#issuecomment-1802779851 didn't actually become a thing, so divisiones are still starting or ending syllables sometimes! However, I understand that we don't want any automatic actions, and it's not difficult to remove the divisio from the syllable. So I'll close this issue!
