### ISSUE TITLE
Moving one or more elements around in quick succession makes Neon unresponsive

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1091]
How to recreate:

1. Using the selection tool of your choice, select more than one element on a staff.
2. Move that selection slightly, and then immediately move it again, without un-selecting it.
3. After 8-10 moves, the elements of your selection will stop snapping to the closest line or space. At that point, no actions work and no work is saved until you reload the page.
4. Sometimes the neumes just disappear, but I haven't been able to reproduce that reliably.

DEMO:

**Unresponsiveness**

https://github.com/DDMAL/Neon/assets/83373378/4f0aa8b3-0eab-4bbf-ba30-7faa9e871e78

**Disappearing neumes**

https://github.com/DDMAL/Neon/assets/83373378/3bdc80d1-cd4d-4b4b-9f99-683307f22868

The example I gave, with moving the same selection over and over again, is just the most reliable way I've found to reproduce the issue. However, the issue also happens when I move different elements around. The main predictor of the issue seems to be speed; if I move stuff around very fast, Neon becomes unresponsive.

I started noticing this issue last week (week of August 7), and I think it's new. I would be surprised if it existed before and I'd just never encountered it.

I'm attaching a medium priority to this issue, because currently the only fix I have is reloading the page, and I sometimes lose work I've done if Neon was unresponsive for longer than I realized.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen I've pushed the changes.

**Comment by JoyfulGen** [comment]
@yinanazhou thank you!!! I've just moved stuff around with much enthusiasm and Neon stayed perfectly calm. Closing issue  now :)
