### ISSUE TITLE
Enhancement request: new bounding boxes narrower

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1093]
At the moment, if you add neume components to a staff, their bounding boxes are quite wide, so if you add a few neume components close to each other all their bounding boxes overlap. 

Since https://github.com/DDMAL/Neon/issues/1055, when I ungroup a syllable, the new bounding boxes look like their width is determined by the width of their syllable. This is awesome! Could something similar happen for new bounding boxes also?

**Comment by yinanazhou** [comment]
Hi @JoyfulGen I've pushed the changes. Please let me know if you like it!

**Comment by JoyfulGen** [comment]
@yinanazhou that's so much better, thank you! Closing issue now :)
