### ISSUE TITLE
Blue circles to resize bounding boxes hide the text

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1098]
When a bounding box is selected, blue circles appear around it to allow the user to resize it as needed. These circles are big-ish, but so far in Einsie they weren't too much of a problem--you can see that they're not actually blocking too much of the text:
<img width="680" alt="blue bobbles big" src="https://github.com/DDMAL/Neon/assets/83373378/e409f419-3d23-4c87-8471-4b0373fe58b3">

However, folio 176r has a couple of staves written in a different hand, and the font is significantly smaller. On this staff, the blue circles hide the text almost completely:
<img width="903" alt="blue bobbles small" src="https://github.com/DDMAL/Neon/assets/83373378/fd6c1fee-b026-4ebd-aa88-1aab5fee156d">

I can imagine that in a different manuscript with a small font throughout, these blue circles could become a significant hindrance.

I have two ideas for fixes:
- Make the circles smaller in general
- Have the circles adapt to the zoom of the page. At the moment, if I zoom in, the glyphs become bigger, but the blue circles do too. I wondered if it would be possible for the circles to zoom in less, so that they don't block the text when the user zooms in. 

@yinanazhou, would either of these work?

**Comment by yinanazhou** [comment]
Hi @JoyfulGen  I've tested a bit, I think the best solution is to make the circle size adjustable. What do you think?

**Comment by JoyfulGen** [comment]
@yinanazhou sounds good, thank you!

**Comment by yinanazhou** [comment]
Hi @JoyfulGen I've pushed the changes!

**Comment by JoyfulGen** [comment]
@yinanazhou I really like it, but it's not working all the time. When I first open a file, the slider doesn't respond. It works after a while, but I can't figure out what makes it wake up. It's not turning the bounding boxes off and on again, nor is it resizing or moving a bounding box or other element on the page. I'm sorry I can't figure it out yet! I'll keep trying. 
Once it works though, it's fantastic! It will be very useful.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen the expected behaviour is when you click on display bbox toggle, the slider appears. This is because the slider is only useful when the bbox is displayed. Please let me know if it works for you.

**Comment by JoyfulGen** [comment]
@yinanazhou I did figure that out, and I think it makes sense! I just mean that when the slider is there, it doesn't always work. I try to click on different parts of it, or click and drag the little circle, and nothing happens...

**Comment by yinanazhou** [comment]
ohhhh no I misunderstood. I will have a look.

**Comment by yinanazhou** [comment]
Hi! I've pushed the fix.

**Comment by JoyfulGen** [comment]
Indeed you have, thank you!! Closing issue now :)
