### ISSUE TITLE
Series of actions makes MEI file disappear

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1105]
Steps:

1. Open the file of your choice, so far it's worked with any file.
2. Check the `BBoxes` box.
3. Interact with a bounding box in any way.
4. Uncheck the `BBoxes` box.
5. Reload the page (doesn't matter if you've saved or not).

The result is that the glyphs don't load and the MEI status stays stuck on "unknown." Interestingly, if you try to download the MEI, no download happens but the MEI status goes back to "VALID" (the glyphs are still invisible). 

Demo:

https://github.com/DDMAL/Neon/assets/83373378/84a08362-c3c1-4569-bf26-8a219aed67e0

So far none of my disappeared files have reappeared, so I'll assign a medium priority to this issue.

**Comment by yinanazhou** [comment]
Hi this happens because you were in `select by bbox` mode, but the mode is only available when the display bbox is toggled. I will fix this ASAP.

**Comment by yinanazhou** [comment]
Hi! I've pushed the changes.

**Comment by JoyfulGen** [comment]
@yinanazhou it's all fixed, thank you! Just to know, is there a way to resuscitate my disappeared files? Or shall I just re-upload them if I need them?

**Comment by yinanazhou** [comment]
All you need to do is to select by syllable, and refresh :)
