### ISSUE TITLE
File system needs a UID

### ISSUE THREAD

**Issue by yinanazhou** [DDMAL/Neon2#1109]
Neon wiki reference: https://github.com/DDMAL/Neon/wiki/Dashboard

**Comment by yinanazhou** [comment]
Hi @JoyfulGen and @annamorphism, I'll soon pushed the changes about file system. Once this is done, all the cached local changes will be gone. Could you please save all the files needed and let me know when I can push the changes?

**Comment by JoyfulGen** [comment]
@yinanazhou you're good to go!

**Comment by yinanazhou** [comment]
Hi @JoyfulGen the updated version is on now. Please let me know if anything weird happens.
