### ISSUE TITLE
Notifications become erratic if you go faster than them

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1110]
If I understand correctly, Neon notifications disappear after five seconds and only three appear at a time. This means that if you perform, say, four actions in 5 seconds, that fourth action will only appear once the first has disappeared. If you perform more than three actions per five seconds for a while, the notifications get a bit overwhelmed. 

A specific case I noticed: 
- Perform 10-15 actions very fast
- Immediately after, purposefully trigger a "grouping failed" notification (by trying to group a neume with a divisio, for example)
- The "grouping failed" notification will appear very quickly BUT it will be followed by successful notifications, even if you're not doing anything anymore.

Demo (where the failed grouping is that last thing I do):

https://github.com/DDMAL/Neon/assets/83373378/f09b4197-58a2-47a3-b867-647700580c69

As I understand it, the correct actions are all getting queued because I'm going faster than the three-notifications-per-five-seconds limit. The failed notification appears to jump the queue, which means that it's followed by the remaining successful notifications. This isn't a huge problem, but it's still peculiar, so here we are.

**Comment by JoyfulGen** [comment]
For future reference, if a user performs a fourth action within five seconds, the first notification immediately disappears and is replaced by the new one, even if its five seconds aren't over yet.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen I've pushed the changes for this issue.

**Comment by JoyfulGen** [comment]
@yinanazhou indeed you have! It's all very smooth now, thank you :) Closing issue.
