### ISSUE TITLE
When deleting the neumes in the first syllable in a toggled-syllable pair, second syllable doesn't get a `syl`

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1116]
In a toggled-syllable pair, the first syllable (Syllable A) has a `syl` element, but the second one (Syllable B) doesn't, because its neumes are sung on the same syllable. If you select either half of the syllable pair with the syllable selector, the entire thing gets selected, so you can't delete either syllable without untoggling them first. This makes sense.

However, if you:
- Use the neume selector;
- Select all the neumes of Syllable A;
- Delete them.

The result is that Syllable B gets untoggled and loses its `follows` tag, but it doesn't get a `syl`, and therefore no bounding box and no text on Neon. It also doesn't respond to commands if you select it with the syllable selector.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen I've pushed the changes.

**Comment by JoyfulGen** [comment]
Fixed! Closing issue now.
