### ISSUE TITLE
Interacting with the neumes within a toggled syllable creates confusion

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1117]
Say a syllable contains neumes A and B. If you add a punctum to neume B, it automatically becomes its own syllable. This is expected behaviour. However, it can create strange situations within toggled syllables. For example:

- Find or create a toggled syllable pair where Syllable A contains two neumes and Syllable B contains one.
- Add a punctum to the second neume of Syllable A and group neumes and neume components.
- You'll notice that that second neume automatically gets removed from syllable A and becomes its own syllable, Syllable C. However, what remains of Syllable A and Syllable B are still toggled. This no longer makes semantic sense, because Syllable A isn't the last syllable of the staff anymore, so it can't be toggled to a syllable on the next staff. Here's a demo, where Syllable A is blue and Syllable B is orange:

https://github.com/DDMAL/Neon/assets/83373378/c43df3c0-a699-4e28-a294-897b88b11d5a

Normally, Neon won't even give you the option of toggling two syllables unless they're the last and first syllables of their staff, so this toggle-sandwich situation is extra weird.

This is actually related to https://github.com/DDMAL/Neon/issues/1115 in that both issues happen because of fact that interacting with a neume within a syllable automatically removes that neume from the syllable.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen I've pushed the changes. Please let me know if there are any edge cases not covered. Thanks!

**Comment by JoyfulGen** [comment]
@yinanazhou it all looks good! The prompt to untoggle always appears when I try to do something weird, so toggle-related confusion is gone! Closing issue now.
