### ISSUE TITLE
Discussion: if obliques are encoded wrong, should Neon care?

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1118]
This is a Neon issue that only exists because of an MEI_encoding bug. I'm putting it here to ask if it's worth fixing just as a fail-safe, or if it doesn't really matter! @yinanazhou this is especially for you. Here it is:

There's currently a soon-to-be-fixed bug in MEI_encoding where obliques are encoded wrong: the first component of the oblique has a `ligated="true"` tag, but the second one doesn't. This results in very funny-looking obliques that Neon does not like at all, so they behave very strangely. Some examples of strange behaviours:

1. Most of the time, the second (lower) punctum of the oblique is visible, but the first (upper) one isn't. If you add a punctum where it looks like one is missing and try to toggle it with the second punctum, it'll just jump to another line and no oblique will appear.
2. Using the neume selector, ungrouping the neume with the wonky oblique in it makes some of the neume components disappear.
3. Deleting the visible (lower) punctum makes the invisible (upper) punctum appear.

As a user, my only solution for dealing with these half-obliques is deleting all involved neumes and re-inputting them. My question though is whether this actually matters, since this is an MEI_encoding issue in the first place. I don't know of any way to create these half-obliques within Neon, so once MEI_encoding stops producing them, the Neon issues will disappear. 

In case you want to have fun, here's a file where I manufactured half-obliques. I named them "hello1," "hello2" and "hello3."
[170r half ligated tests.mei.zip](https://github.com/DDMAL/Neon/files/12765301/170r.half.ligated.tests.mei.zip)

**Comment by annamorphism** [comment]
I'm having deja vu all over again. This weird bug happened ages and ages ago and we fixed it, I thought! Why is it here again?

**Comment by JoyfulGen** [comment]
@annamorphism I'm producing these files in staging, where the MEI_encoding job has been going through some changes. As I understand it, lots of bugs will be fixed very soon! I only brought this issue up because it has confusing consequences for the user in Neon. 

(Also a very similar thing was happening when we first implemented the width factor and I made a mistake when filling out the csv file... so that might be triggering your déjà vu)

**Comment by JoyfulGen** [comment]
Ok I take it back!! Your déjà vu is completely correct, this is a width factor mistake all over again. Apologies! However, I feel like it's the opposite of what it was before. Here's what I mean:

In the csv file, the width column specifies how the components of a given neume should be arranged. For example, a clivis has a width of [1,1], because its two components are one after the other. A podatus is [2], because the two components are stacked. A scandicus is [1,2], because the first component is alone and the next two are stacked. Hopefully that makes sense! 

Anyway, when this was implemented I gave the oblique a width of [1,1] (I think). But Neon didn't like that, which is what resulted in the issue you remember. So I changed it to a width of [1] and everyone was happy.

Now, however, you made me wonder whether the width was a problem again, now that I'm using rodan_staging. So I changed the width to [2] and the obliques look fine?!?! Rodan_production is being very slow right now so I can't double-check this, but I'll update the issue as soon as possible!

In the meantime, my original question still stands.

**Comment by JoyfulGen** [comment]
I made a separate issue about oblique width here: https://github.com/DDMAL/Rodan/issues/1086

**Comment by yinanazhou** [comment]
I think this is more like an issue about the MEI encoding job in Rodan? Should Neon check if the obliques are encoded correctly like it checks the linked syllables?

**Comment by JoyfulGen** [comment]
It is an MEI encoding issue! But I think a check would be useful. Just a little heads-up message that obliques are encoded incorrectly and might behave weirdly. Does that make sense?

**Comment by yinanazhou** [comment]
Hi! I've pushed the changes

**Comment by yinanazhou** [comment]
Hi @JoyfulGen could you please confirm that this issue can be closed?

**Comment by JoyfulGen** [comment]
@yinanazhou it's confirmed! Thank you :)
