### ISSUE TITLE
Dashboard: Sample files don't load.

### ISSUE THREAD

**Issue by fujinaga** [DDMAL/Neon2#1125]
Clicking on any of the sample files don't work.
<img width="885" alt="image" src="https://github.com/DDMAL/Neon/assets/1031785/d48cef9b-7506-42f4-b9ea-6bafc11f8389">

**Comment by yinanazhou** [comment]
I cannot reproduce this issue in Chrome and Safari. Sometimes the image takes a while to load.

**Comment by fujinaga** [comment]
It’s here, correct?
https://ddmal.music.mcgill.ca/Neon/dashboard.html
It doesn’t load on my iPad or iPhone either.

Anything I can check on my end?

On Nov 1, 2023, at 9:55 AM, Yinan Zhou ***@***.***> wrote:



I cannot reproduce this issue in Chrome and Safari. Sometimes the image takes a while to load.

**Comment by yinanazhou** [comment]
I just checked on iPhone. It needs a double-click to open a folder/file, same on web page. Single click is just to select a file, so that you can make some changes, like rename or move.

**Comment by fujinaga** [comment]
Ah ha! That works.

But that’s counter intuitive.
Why do you want to modify sample files? I can delete these files?


On Nov 1, 2023, at 10:26 AM, Yinan Zhou ***@***.***> wrote:



I just checked on iPhone. It needs a double-click to open a folder/file, same on web page. Single click is just to select a file, so that you can make some changes, like rename or move.

**Comment by yinanazhou** [comment]
You cannot modify or delete sample files, but these actions are available for other files that the user uploads.

**Comment by fujinaga** [comment]
Why is that? Because the folder is owned by someone else? It's not clear.
Also, the message I get when I tried to delete doesn't make sense.
<img width="1036" alt="Screenshot 2023-11-01 at 1 26 03 PM" src="https://github.com/DDMAL/Neon/assets/1031785/f80eb805-93a3-48aa-b693-4b435daab583">

**Comment by yinanazhou** [comment]
It's because the samples folder is provided by the website and not the user. The message is wrong. I will make the options disabled.

**Comment by annamorphism** [comment]
> Ah ha! That works. But that’s counter intuitive. 

And here I thought I was the only one who thought this!
