### ISSUE TITLE
Discussion: delete folders in dashboard

### ISSUE THREAD

**Issue by yinanazhou** [DDMAL/Neon2#1126]
This is mostly a question to @JoyfulGen and @annamorphism.

Now if the user wants to delete a folder, neon will give an alert:

![image](https://github.com/DDMAL/Neon/assets/74484576/b8a30843-a6ee-4da8-ba58-63b3390734f7)

But I'd prefer if it deletes all the files in the selected folder and the folder itself when I manage my files. I'd like to hear the users' perspective. Thanks!

**Comment by JoyfulGen** [comment]
I agree that it's useful to be able to delete a folder and all its files! I would just like to make sure that there's a message alert to confirm that the user actually wants to do that. Is that ok?

**Comment by fujinaga** [comment]
I think deleting a non-empty folder is fine, as long as there’s a recoverable trash can.
Otherwise, I’d keep it as it is.

**Comment by annamorphism** [comment]
> I agree that it's useful to be able to delete a folder and all its files! I would just like to make sure that there's a message alert to confirm that the user actually wants to do that. Is that ok?

This is exactly what I was going to suggest! I think users might well want to delete a whole folder (otherwise why organize them into folders in the first place?) but they should get a warning not to do it by accident.

**Comment by yinanazhou** [comment]
Found related issue #834, closing this issue
