### ISSUE TITLE
Folders apparently gone from Neon dashboard

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1134]
I had five folders on my Neon dashboard, but when I looked at it today only three remained. I then refreshed the page and another one disappeared! I'll keep investigating to try to find the chain of actions that did this. @yinanazhou do you know if there's any way I could get my folders back?

**Comment by yinanazhou** [comment]
I'm so sorry that this has happened.. I may know the reason, but you won't be able to get the folders back.. I feel like we really need to have a trash bin folder now.

**Comment by JoyfulGen** [comment]
No worries!! I had everything backed up like a good little tester. Big fan of the trash bin idea!

**Comment by yinanazhou** [comment]
Related issue #834, closing this issue
