### ISSUE TITLE
Toggling issues arise if an empty syllable is involved

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1138]
There are now checks in place that prevent a user from interacting with toggled syllables without untoggling them first. However, I've just realized that the "Remove empty syllables" button gets around those checks. If you have a syllable toggled to an empty syllable, removing the empty syllable without untoggling it first leaves the other syllable toggled with nothing. The remaining syllable (the one that's toggled with nothing) becomes unresponsive and clicking on it doesn't do anything. 

I'm not sure that asking the user to untoggle the empty syllable before removing it works in this case, because it's hard to figure out which syllable the empty syllable is toggled with, so untoggling them is tricky. Would it be possible instead to make it so that if the user removes an empty syllable that's toggled with a syllable on the page, the remaining syllable automatically loses its `<precedes>` or `<follows>` tag? 

An example where syllable "hello" is toggled with an empty syllable on the next staff. If you remove empty syllables, "hello" will become unresponsive.
[168r_toggled_with_empty.mei.zip](https://github.com/DDMAL/Neon/files/13391881/168r_toggled_with_empty.mei.zip)

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, is this file a straight-out-of-mei-encoding file? I've noticed some unexpected errors in the file. Like this:
![image](https://github.com/DDMAL/Neon/assets/74484576/43bd55b7-0241-4ec1-8e66-7c6ec2653740)

**Comment by JoyfulGen** [comment]
@yinanazhou it is, but empty syllables have just been successfully removed from mei_encoding, so it should all be good now!

**Comment by yinanazhou** [comment]
Hi, I've pushed changes for this issue. Please let me know if it works. Thanks.

**Comment by JoyfulGen** [comment]
It works, thank you! Closing issue now.
