### ISSUE TITLE
Neon sometimes detects out-of-bounds glyphs that it can't remove

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1147]
It sometimes happens that when I open a file, I get a "This folio has glyphs placed out of bounds!" warning from Neon. But then if I click on `Remove out-of-bounds glyphs`, Neon tells me that "There are no out-of-bounds glyphs to remove."

It happens with this file: 
[232v with staging test neume on two staves.mei.zip](https://github.com/DDMAL/Neon/files/13545504/232v.with.staging.test.neume.on.two.staves.mei.zip)

This file also has an element with coordinates (0,0,0,0), right at the top of the list of bounding boxes. This makes me wonder if this issue is connected to this one: https://github.com/DDMAL/Rodan/issues/643. @yinanazhou could this be the case?

**Comment by yinanazhou** [comment]
Yes, I think this issue is caused by the MEI encoding job. But I can add a check in Neon and give user a way to correct it.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I just realized that this all-zero zone is not linked to any elements in the file. Now I wonder what might be the best way to handle this. I can add a check to loop through all the zone elements to check if they are all-zero, and add an MEI action to remove all-zero zones and its corresponding elements if any. How does that sound to you?

**Comment by fujinaga** [comment]
Yes, you can do that as a temporary measure, but I would post an issue to find out how these all-zero zones are generated and stop them.

**Comment by JoyfulGen** [comment]
@fujinaga, done! https://github.com/DDMAL/Rodan/issues/1116

@yinanazhou the plan sounds good! Question though: most of the time, the all-zero zone refers to the first syllable's bounding box. If Neon will automatically delete all-zero zones, does that mean it'll delete the syllable as well?

**Comment by yinanazhou** [comment]
@JoyfulGen unfortunately yes. I'll pushed the changes for you to test. I can revert it if you like.

**Comment by yinanazhou** [comment]
After further testing, I found that the out-of-bounds glyphs are detected while loading the file, but Neon automatically removes the last element in the file (#673), so that when the user tries to remove the out-of-bounds glyphs, Neon cannot find the glyphs anymore. 

Question for @timothydereuse, is it better to force the MEI encoding job to make the last element a `<custos>`? In the example file provided above, a whole `<syllable> `element is removed.

**Comment by JoyfulGen** [comment]
@yinanazhou so sorry to arrive late, but what changes have you pushed? Should the all-zero zones be gone from the start, or should the "remove out-of-bounds glyphs" option remove them?

**Comment by yinanazhou** [comment]
Hi @JoyfulGen no problem. So now Neon will remove the all-zero zones when loading files. I'm still trying to find a way to handle the out-of-bounds glyphs. Neon automatically remove the last element in the document, but the zones are not removed, so Neon can detects something is out-of-bounds, but it cannot remove them.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen I've pushed the changes to remove the zones for the last element in Neon. This should fix the false alarm.

**Comment by JoyfulGen** [comment]
It does indeed! Thank you very much. You can close the issue now as far as I'm concerned.
