### ISSUE TITLE
Feature request: the ability to select an empty MEI file when uploading files to Neon

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1151]
At the moment, a user always has to upload their own MEI file to open the Neon workspace and make edits. However, Neon could sometimes be used to create an MEI file from scratch. To account for this, it would be useful for the user to be given an empty MEI file, rather than have to upload one themselves.

I was imagining having a little checkbox in the MEI column of the Unpaired Documents section that says something like "use blank MEI file"; if the user checks it, they don't need to upload their own MEI file, only the image. @yinanazhou @annamorphism what do you think? Would this be possible?

**Comment by annamorphism** [comment]
I think this sounds like an excellent feature!! Would use.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen I've pushed all the changes related to this issue. Please let me know if it works as expected.

**Comment by JoyfulGen** [comment]
@yinanazhou it looks great, thank you! This will be super useful. You can close the issue as far as I'm concerned!
