### ISSUE TITLE
When deleting a clef, the clef only disappears after another action is performed

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1157]
Thank you @PhoebeDM for finding this one! It started happening sometime last week, sources tell me. To reproduce:

- Select a clef in a straight-outta-OMR file.
- Delete the clef (with keyboard shortcut or by clicking on the button); nothing happens.
- Perform any other action.
- The clef disappears.

It seems like Neon doesn't register the deletion until another action is performed, because if I delete a clef and undo my action, Neon tells me there are no actions to undo.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen I've pushed the changes :)

**Comment by JoyfulGen** [comment]
@yinanazhou fixed! Issue can be closed now, as far as I'm concerned :)
