### ISSUE TITLE
Liquescents not working

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1169]
Liquescents on Neon aren't getting their `curve` attribute, so they're being recorded as puncta. If you change a note head to a liquescent C or A, or if you input a liquescent C or A, it'll look fine at first, but if you reload the page the liquescents will become puncta. In the MEI file, the note looks like a punctum (I think), even though you made it a liquescent.

This is a slightly urgent issue, because I've found no other way to add liquescents to a file at the moment.

**Comment by yinanazhou** [comment]
Working on it!

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, to follow up your question about liquescent not showing up, it is because we were encoding liquescent wrong before. 

Before liquescent is encoded as:
```
<neume>
    <nc oct="2" pname="d" tilt="n"/>
    <nc oct="2" pname="c" curve="a" />
</neume>
```

But it should be:
```
<neume>
    <nc oct="2" pname="d" tilt="n"/>
    <nc oct="2" pname="c" curve="a">
        <liquescent />
    </nc>
</neume>
```

After I fixed this in verovio, the liquescents in the old files won't show up because `<nc>` doesn't have a `<liquescent>`, so verovio doesn't know which note type it should be. I will push a temporary fix in Neon to automatically add `<liquescent>` when the `<nc>` has a curve value. And we also need to fix this in the MEI encoding job in Rodan.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've pushed the changes. Liquescents should be good now.

**Comment by JoyfulGen** [comment]
@yinanazhou indeed you have, thank you! It all looks good.

About the mei_encoding problem, I have question: in the csv file I use for the mei_encoding job, liquescents do have the `<liquescent>` attribute. But when files come out of OMR, they don't have the attribute. So the issue is in the mei_encoding job itself, right?

**Comment by JoyfulGen** [comment]
@PhoebeDM liquescents are good now!

**Comment by fujinaga** [comment]
> @yinanazhou indeed you have, thank you! It all looks good.
> 
> About the mei_encoding problem, I have question: in the csv file I use for the mei_encoding job, liquescents do have the `<liquescent>` attribute. But when files come out of OMR, they don't have the attribute. So the issue is in the mei_encoding job itself, right?

@yinanazhou, can you work with @timothydereuse to resolve this? Perhaps create a separate issue in MEI_encoding?

**Comment by yinanazhou** [comment]
> @yinanazhou, can you work with @timothydereuse to resolve this? Perhaps create a separate issue in MEI_encoding?

Will do!

**Comment by yinanazhou** [comment]
Corresponding Rodan issue: https://github.com/DDMAL/Rodan/issues/1123

**Comment by PhoebeDM** [comment]
Hiya @yinanazhou and @JoyfulGen, liquescents aren't working again/reverting to puncta...I'm in 151r, anything I should try?

**Comment by yinanazhou** [comment]
@PhoebeDM I probably mixed verovio versions. I will quickly update it and let you know when it's done!

**Comment by yinanazhou** [comment]
Hi @PhoebeDM I've pushed the changes. It should be good now.

**Comment by JoyfulGen** [comment]
@yinanazhou liquescents work!
