### ISSUE TITLE
Request: give the ID of glyphs placed out of bounds

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1174]
When Neon alerts the user that there are empty syllables in the file, it also gives the IDs of those syllables in the error log. Could it do the same for glyphs placed out of bounds? It would help me find them and explore the problem (if there is one).

**Comment by yinanazhou** [comment]
Hi I've pushed the changes.

**Comment by JoyfulGen** [comment]
@yinanazhou that's perfect, thank you! You can close the issue as far as I'm concerned.
