### ISSUE TITLE
New glyphs rendered to the right of the cursor

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1175]
It used to be that when you clicked on the folio to input a glyph, the glyph would be generated right under the pointiest bit of the cursor. However, they're now being generated so that their left side aligns with the left side of the cursor, which means that they're always a liiiiittle to the right of where you want them to be.

But divisiones are different! Divisiones render completely to the left of where you click. (This has actually been true for a super long time, I just initially forgot to report it and then got completely used to it. Sorry!)

**Comment by JoyfulGen** [comment]
@PhoebeDM fyi!

**Comment by yinanazhou** [comment]
Hi @JoyfulGen I've pushed the changes:)

**Comment by JoyfulGen** [comment]
@yinanazhou that is so satisfying!! Thank you for the fix :) You can close the issue as far as I'm concerned!
