### ISSUE TITLE
If you untoggle two linked syllables, the new bounding box is more opaque than the rest

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1177]
There was an issue a while ago where bounding boxes were more opaque sometimes. Not sure where that issue went, but it's happening again!

Steps:
- Find or create a toggled-syllable pair;
- Untoggle that toggled syllable;
- A new bounding box will appear for the second half of the now-untoggled pair;
- Observe how it is more opaque than the rest!

This is 100% not a problem, because it doesn't affect usage in any way. It's just wonky!

@PhoebeDM fyi

**Comment by yinanazhou** [comment]
Hi @JoyfulGen I've pushed the changes.

**Comment by JoyfulGen** [comment]
@yinanazhou all fixed, thank you!
