### ISSUE TITLE
Any neume components following a liquescent in the same neume can't be moved

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1180]
If a neume looks like so:

Some neume components
A liquescent
Some more neume components

All of the nc's after the liquescent can't be moved. You can click and drag them, but as soon as you let go they snap back to their original position. If you try to move the whole neume, the liquescent stays where you put it, but the nc's after it snap back to where they were before. If there are nc's before the liquescent, they can be moved just fine. This is true of liquescents that are in the straight-outta-OMR file and liquescents that are added to the file.

Demo: 
https://github.com/DDMAL/Neon/assets/83373378/5fe8bc30-6d5a-4b15-bbe0-b6ce10476908

The workaround for now is to ungroup everything, move the neume components, then regroup as necessary.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen I've pushed the changes.

**Comment by JoyfulGen** [comment]
@yinanazhou looks good to me!
