### ISSUE TITLE
"Untoggle invalid toggled syllables" partially untoggles valid toggled syllables

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1203]
If you click on the "Untoggle invalid toggled syllables," valid toggled syllables get affected too: the second half gets a `syl` element, but the `precedes` and `follows` tags remain, so that in Neon we get syllables that are toggled, but both have bounding boxes.

Here's an example in the MEI, from folio 043r.

Here's the syllable "what" before untoggling invalid toggled syllables:

<img width="906" alt="143r toggled syl before" src="https://github.com/DDMAL/Neon/assets/83373378/7309ee12-3066-4ed8-87ee-69222325a409">

And here it is after untoggling invalid toggled syllables:

<img width="848" alt="143r toggled syl after" src="https://github.com/DDMAL/Neon/assets/83373378/98d68783-26e6-4791-bd9c-7ed14f0c606e">

This is the original MEI file: 
[043r.mei.zip](https://github.com/DDMAL/Neon/files/14853821/043r.mei.zip)

All you have to do to replicate this issue is find an ordinary toggled syllable and then click on "Untoggle invalid toggled syllables." The second half of the toggled syllable will get a `syl` element and a corresponding bounding box, but if you click on either half of the syllables you'll see that they're still toggled to each other.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, so sorry for the inconvenience. I've pushed the changes.

**Comment by JoyfulGen** [comment]
All good, thank you!! Issue fixed from what I can see.
