### ISSUE TITLE
Custodes only partially acknowledge octave displacement

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1205]
If you displace an octave up or down using the "Displace Octave" dropdown menu, the custodes can't quite handle it. Hovering over them gives the right octave information, but if you drag and drop them somewhere they hop up (or down, depending) an octave. From what I can tell, the custos calculates its pitch based on the old clef, but then jumps to that pitch in the new clef.

In this video, I displaced the F clef down an octave, from F3 to F2. So if I drag the custos to the first line of the staff, it calculates that pitch based on the old F3 clef, which gives a B2. However, with the new clef, a B2 is above the top line of the staff, so that's where the custos goes. You can see that wherever I put it, it always hops up an octave. Inversely, if I had displaced the clef _up_, the custos would be jumping _down_.

https://github.com/DDMAL/Neon/assets/83373378/1d3ab4e8-8a24-4602-893f-a4867afc6909

I'm sorry for not spotting this one sooner! Lame, Gen.

**Comment by annamorphism** [comment]
it's like a little nostalgic throwback to #655 ! (But not quite the same.)

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've pushed the changes to neon staging.

**Comment by JoyfulGen** [comment]
@yinanazhou it looks good! It all works normally now, thank you
