### ISSUE TITLE
'Untoggle invalid syllables' button not unttogling invalid syllables

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1209]
I uploaded Salzinnes folio A38v for review and I got three invalid syllable notifications; all three syllables involved have a `precedes` tag that refers to a syllable that doesn't exist. Because of this, I can't select these syllables on the page. However, when I click on 'Untoggle invalid syllables', nothing happens!

Video demo: 

https://github.com/DDMAL/Neon/assets/83373378/d662a9f3-7819-4741-89ec-b237894f9f6e

This is the error message on Neon: 
- `<syllable>` (te) with xml:id: m-833d80cb-ecf1-4f0c-b8fc-03b49373368a is missing the following part
- `<syllable>` (nes) with xml:id: m-4f2f3d1f-1b08-48f8-a393-240f8b03a77f is missing the following part
- `<syllable>` (gi) with xml:id: m-caf26c17-8599-4921-b461-aefd3b805faa is missing the following part

And this is the MEI file I uploaded: 
[CDN-Hsmu_M2149.L4_A38v.mei.zip](https://github.com/DDMAL/Neon/files/15274582/CDN-Hsmu_M2149.L4_A38v.mei.zip)

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've pushed the changes to Neon staging.
