### ISSUE TITLE
[Neon staging] Files don't order themselves automatically on the dashboard

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1222]
On production, if I upload a new file to an existing folder, it automatically goes to the correct position in the numerical order. On staging however, new files just get added to the end of the list, so there's no numerical order.

Here's what my staging dashboard looks like now:

<img width="1439" alt="Neon staging dashboard" src="https://github.com/DDMAL/Neon/assets/83373378/0ec6ae7c-908f-4675-8fc6-3e5248220ae9">

Interestingly enough, I uploaded 030r, 030v, 031r, 032r, and 032v all at the same time, but they're also not in numerical order.

**Comment by yinanazhou** [comment]
Is this still happening to you? I can't really reproduce this issue.
![Screenshot 2024-06-21 at 11 56 11 AM](https://github.com/DDMAL/Neon/assets/74484576/c1fe76bc-0772-4e6d-8a28-ef65f8d81196)

**Comment by JoyfulGen** [comment]
I explored a bit more and found that this issue also only occurs on Firefox. On Chrome, the files order themselves no problem!

**Comment by yinanazhou** [comment]
Question: does Neon production order files on Firefox?

**Comment by annamorphism** [comment]
I uploaded "Eksteen" "riesencodex" "pepys fragment" and "image" at the same time on Firefox,  listed in that order in the window, and as you can see they are ordered with the pre-existing "I 95 1r" sandwiched nicely in the alphabetical order. So I think this does order properly on production. 

<img width="1063" alt="image" src="https://github.com/DDMAL/Neon/assets/67451875/234f996d-2292-4129-ac65-5c48792cd8e4">

**Comment by yinanazhou** [comment]
I'm using firefox and it orders files automatically on Neon staging.
![Screenshot 2024-06-25 at 10 15 40 AM](https://github.com/DDMAL/Neon/assets/74484576/ba3baea2-9e07-4345-aa65-561c0c71f52f)

**Comment by JoyfulGen** [comment]
Wha... my firefox is rude! But since it seems to be only a Gen problem, then it's all good!

**Comment by yinanazhou** [comment]
@JoyfulGen could you try to clean cache and hard reload (`shift` + click refresh button)? Maybe it will help.

**Comment by JoyfulGen** [comment]
Doesn't seem to :(

**Comment by JoyfulGen** [comment]
Well, somewhere along the line this got fixed for me! All files are ordering properly on all browsers. Closing issue!
