### ISSUE TITLE
[Neon staging] Some files say "unknown" and never appear... but I don't know why :(

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1225]
Some of the files I upload to staging look like this when I open them:

<img width="1440" alt="Screenshot 2024-06-19 at 3 16 18 PM" src="https://github.com/DDMAL/Neon/assets/83373378/5e2aa128-e7be-4282-b9f9-ea357c400799">

And some look fine! I think _maybe_ it has to do with the timeline (older files work, newer files don't), but I can't confirm that because a) I don't have my old DDMAL notebook on me and b) I can't currently access my rodan account, so I can't check dates. For now, all I can do is give you some example files:

Here are a couple that work:
[048r.mei.zip](https://github.com/user-attachments/files/15901533/048r.mei.zip)
[114r.mei.zip](https://github.com/user-attachments/files/15901535/114r.mei.zip)

And here are a couple that don't:
[037r.mei.zip](https://github.com/user-attachments/files/15901553/037r.mei.zip)
[170r.mei.zip](https://github.com/user-attachments/files/15901559/170r.mei.zip)

**Comment by yinanazhou** [comment]
Hi I've pushed the changes to neon staging.

**Comment by JoyfulGen** [comment]
Huzzah!! They work!! You can close the issue as far as I'm concerned :)
