### ISSUE TITLE
[Neon staging] Moving a neume component makes its neume move up a step or two

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1227]
Three similar behaviours:

1. If you use the neume component selector and move a neume component up or down, all the neume components of the neume it belongs to will move up.
2. If you use the neume selector and move a neume up or down, all the neumes of the syllable it belongs to will move up.
3. If you use the syllable selector and move a syllable up or down, all the neumes in that syllable will move up.

This only happens when you move a neume component/neume/syllable for the first time. After that, you can move it as you like without issues. Also, if you create your own neume and move it, it'll behave normally.

Demo:

https://github.com/DDMAL/Neon/assets/83373378/93a97300-0945-4cf4-ac37-e4e34f3b3764

**Comment by yinanazhou** [comment]
This is related to #1223

**Comment by yinanazhou** [comment]
This issue is fixed. Waiting on rism to merge changes to develop.
