### ISSUE TITLE
[Neon staging] Custodes added after clef octave displacement appear an octave too high/low

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1235]
If you displace the octave of a clef, a custos that's already on the staff will adapt as expected. However, if you add a custos to a staff where the octave is already displaced, it'll appear an octave too high (if the clef is an octave lower) or too low (if the clef is an octave higher). After that, you can move it to where it's supposed to go and it'll stay there.

**Comment by yinanazhou** [comment]
Just wanted to confirm, this only happens to custodes? what about neumes?

**Comment by yinanazhou** [comment]
No, it doesn't happen to neumes

**Comment by yinanazhou** [comment]
The changes has been merged!
