### ISSUE TITLE
[Staging] Moving a neume component causes the other nc's of its syllable to move up or down a step or two

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1250]
If you move one of the neume components of a syllable, the rest of the syllable will move up or down a step or two. After that you can move the nc's of that syllable without any problem! Basically every syllable has to be messed with once before it behaves.

Demo:

Uploading Moving nc makes syllable jump.mov…

**Comment by JoyfulGen** [comment]
Update: moving an entire syllable with the syllable selector makes all of the following glyphs before the next clef move too.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, the most recent changes has just been merged. Could you please test again?

**Comment by JoyfulGen** [comment]
Heya @yinanazhou, the issues are still there, but a bit different; the neume component issue is the same, but now if you move an entire syllable it only makes that syllable move, not all of the syllables before the next clef.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, could you upload a new recoding for this?

**Comment by JoyfulGen** [comment]
Sure thing! In the syllable highlight, I first used the neume component selector to move individual nc's around; you can see that when one nc moves, its syllable moves too. I then used the syllable selector, and you can see that when I try to move a syllable, the whole thing moves up much higher than where my cursor is. Also, because some nc's are moving up bigger intervals, the neumes lose their correct shape.

https://github.com/user-attachments/assets/8d886f5a-4c0a-4b0c-8363-6f096f461922

Note: While recording this I found another issue, detailed here: https://github.com/DDMAL/Neon/issues/1252

**Comment by JoyfulGen** [comment]
@yinanazhou this is fixed! I can move neume components, neumes, and syllables, and everything is behaving completely normally.
