### ISSUE TITLE
Add att_visual diagonalright attribute to <nc>

### ISSUE THREAD

**Issue by ATranimal** [DDMAL/Neon2#14]
In compliance with MEI 4.0, diagonalright needs to added as an attribute for <nc> tags.

**Comment by JRegimbal** [comment]
In verovio [ade1bf3](https://github.com/ATranimal/verovio/commit/ade1bf33832f8c642417a5db353f35511a71be0f)

Needed to add AttNcVis to Nc class, read those attributes in `iomei.cpp`. Also added glyphs to Leipzig and enabled punctum virga in Bravura.

`diagonalright` attribute can be read but is only used when rendering punctums with `diagonalright="u"`.
