### ISSUE TITLE
Update the neon demo page

### ISSUE THREAD

**Issue by zoemcl** [DDMAL/Neon2#175]
The current version of neon on the DDMAL demo page is very old (before summer 2017) and should be updated to the new version of Neon.

http://ddmal.music.mcgill.ca/neon

**Comment by zoemcl** [comment]
@emilyhopkins @vigliensoni

**Comment by emilyhopkins** [comment]
Hi! I can fix this. Just a couple things:

- What should the new demo link be?
- Do you want the description changed at all too?
- I can add some names to "Neon.js is developed by:"
Andrew Tran
Zoé McLennan
Juliette Regimbal 
(am I missing anyone?)
- do you want me to add Gabriel or someone to project managers?

Thanks!

**Comment by zoemcl** [comment]
@emilyhopkins thanks!

- The link should redirect to a version of Neon that is the master branch of the Neon2 repository (this repository). The master branch is currently just the MEI viewer, but a stable version of the editor should be released in the next week.
- We should add to the description that it is rendered using Verovio and possibly add a link to it's repo/website.
- I don't think you're missing anyone in the developers.
- And yes I think Gabriel should be added!

Let me know if you need any more information.

**Comment by zoemcl** [comment]
@emilyhopkins it seems we will be moving the demo page to github pages so that is what the link should redirect to. we will let you know when the page is up and running.

**Comment by JRegimbal** [comment]
The page is running at [ddmal.github.io/Neon2](https://ddmal.github.io/Neon2).

**Comment by emilyhopkins** [comment]
OK! I think I found all the links -- I changed the links to the issues pages, etc., so everything should be linked to Neon2 now. I changed the contact person to me instead of Alastair Porter -- I can always forward things to you (or him!!) but I don't think he's been working on Neon for awhile now... 

http://ddmal.music.mcgill.ca/neon

Please take a quick look and make sure everything is as you intended. I added the bit about Verovio and shortened/clarified the description a little.

**Comment by zoemcl** [comment]
@emilyhopkins thanks! There are several instances of "Neon.js" that should be changed to Neon2: In the title, in the description, in the first bullet point of contributing code, in the feedback, and in the sponsors. 

Other than that everything looks good!

**Comment by emilyhopkins** [comment]
OK, I wasn't sure about that. There is now no more "neon.js" anywhere! I will leave it to you to make sure everything is as you want it, you can close the issue if so! Thanks!
