### ISSUE TITLE
Staff selection button gets cut off on narrower screens

### ISSUE THREAD

**Issue by JRegimbal** [DDMAL/Neon2#183]
On narrower screens the selection buttons keep their same size and horizontal layout and ultimately the staff select button gets cut off and cannot be used.

**Comment by JRegimbal** [comment]
Temporary fix in 4ab791a. Added a horizontal scrollbar to the selection options so we can access all of them, but we still need to actually change the whole layout to be more responsive.

**Comment by zoemcl** [comment]
fixed in 81e621ecc3a74fecd51c908c1f8d26fc3faabf7f
