### ISSUE TITLE
Try to refine insert even more

### ISSUE THREAD

**Issue by zoemcl** [DDMAL/Neon2#193]
It is already quite good so this is not an urgent issue, but people have been noticing a few inconsistencies during insertion. Inserted neume components will still often snap to the staff line just above the one that was intended.

**Comment by JRegimbal** [comment]
Issue is not in calculating insert. Issue comes with staff rendering. For some reason the staff is rendered with each line a bit higher than it should be, with the error increasing for each successive line. (The highest line is fine, the next highest is a bit off, the next is more off, etc.) The insert is being calculated based on where the lines *should* be, not where it is. This is also why the error only appears in lower lines.
