### ISSUE TITLE
Implement Zoom

### ISSUE THREAD

**Issue by zoemcl** [DDMAL/Neon2#22]
Implement zoom so that the background layer and neume layer zoom simultaneously to the same level

**Comment by JRegimbal** [comment]
Zooming and panning for svg implemented using d3 in [this branch](https://github.com/DDMAL/Neon2/tree/feature/zoom-and-pan).

**Comment by JRegimbal** [comment]
Can drag to pan if we do something like change the listener on shift press. Version of this in [here on lines 23-29](https://github.com/DDMAL/Neon2/blob/presentation/public/src/Neon.js).

**Comment by ATranimal** [comment]
As of 1acfda2f22b5716443e2116b82004e543802356f
Zoom works with slider as well as hotkeys
