### ISSUE TITLE
Remove white border and sides and top of score container

### ISSUE THREAD

**Issue by zoemcl** [DDMAL/Neon2#295]
There is a small white border on the left side, right side and top of the container containing the bgimg and the svg output. It was not very apparent before but now that the the notifications have been moved to inside the container.

**Comment by JRegimbal** [comment]
This is how the issue looks.

![Screenshot_2019-05-02 Neon3](https://user-images.githubusercontent.com/6963142/57085032-67f75700-6cc9-11e9-9481-894b9fbde4a7.jpg)
