### ISSUE TITLE
Be able to drag Staff anywhere within black border

### ISSUE THREAD

**Issue by zoemcl** [DDMAL/Neon2#296]
This is not an urgent fix since the current functionality is very good, but it would be nice to be able to drag the staff by clicking anywhere within the the black border that is generated when a staff is selected. Currently the staff can only be dragged if we click on a neume or on a staffline, but users should also be able to drag it when they click on the background within the black border as well.

**Comment by JRegimbal** [comment]
We might be able to do this by dispatching a mousedown event on the staff SVG when we click on part of the staff outside the SVG elements.

**Comment by JRegimbal** [comment]
Tried just sending a `mousedown`. That does trigger the start action of the drag handler, but the problem is none of the `mousemove` actions following that are associated with the staff or any SVG element.
