### ISSUE TITLE
Grouping part of an existing group should create a new group or groups

### ISSUE THREAD

**Issue by JRegimbal** [DDMAL/Neon2#299]
Right now wanting to take what is grouped as a syllable or neume and split it into two or more syllables or neumes requires ungrouping every part into separate syllables and neumes respectively, then regrouping each part.

It would be quicker to allow selecting part of a syllable or neume and being able to group that selection into its own syllable or neume in one step. If it makes the original syllable or neume non continuous, grouping should either not be allowed or should regroup into continuous parts.
For example if three neume components are in neume A like `A A A` and we group the second into B as `A B A`, this action should yield `A B C` since otherwise neume A would be split by neume B.

**Comment by zoemcl** [comment]
Another side effect of this is if that if a new group is created within another group excluding only one of the original elements, that excluded element gets deleted. For example  if the original group is **A B C D**   and we group **A B C** , **D** will be deleted from the page.
