### ISSUE TITLE
clarify naming

### ISSUE THREAD

**Issue by rettinghaus** [DDMAL/Neon2#354]
It is not clear from the README if version 3.0.0 is "Neon3" or still "Neon2". 
Please clarify.

**Comment by JRegimbal** [comment]
@rettinghaus Sorry for the delay. Currently version 3.0.0 can be considered Neon2. However to avoid this kind of ambiguity in the future the software currently called Neon2 will be renamed to Neon and all references to Neon2 or Neon3 will be changed to this, including in the name of the repository. Version numbers will continue to be the same as they are currently.

**Comment by rettinghaus** [comment]
Thanks! Was confused, mainly because you presented "Neon2" and showed Neon3 features.

**Comment by JRegimbal** [comment]
Yeah the trouble is we used Neon2 to refer to both the project itself and the version 2 release of Neon.
