### ISSUE TITLE
divaview refreshing after action

### ISSUE THREAD

**Issue by jacob-hutnyk** [DDMAL/Neon2#360]
neon isn't refreshing after an editor action is performed when in divaview mode. you have to scroll up to a different page and scroll back down in order to see the editor action's result

**Comment by jacob-hutnyk** [comment]
fixed in [branch 360](https://github.com/DDMAL/Neon2/tree/360) most recent commit. Not merging into develop since the unified editing code is not fully tested

**Comment by JRegimbal** [comment]
@jacob-hutnyk please make a pull request into feature/343.
