### ISSUE TITLE
Add developers and help to navbar

### ISSUE THREAD

**Issue by zoemcl** [DDMAL/Neon2#37]
Add a developers dropdown and a help link to the navbar. Help should redirect to the Neon2 wiki.

**Comment by JRegimbal** [comment]
Added an [issue guide](https://github.com/DDMAL/Neon2/wiki/Issues) to the wiki.

**Comment by zoemcl** [comment]
added help button that redirects the the Neon2 wiki. Developers will be listed in the wiki.
