### ISSUE TITLE
Implement neume groups

### ISSUE THREAD

**Issue by ATranimal** [DDMAL/Neon2#4]
Groups of neumes should have a separate image

**Comment by ATranimal** [comment]
*need to refactor NeumeGroup information onto its own class instead of in neume.cpp to reduce memory usage
*think about rendering of neume groups -> individual SVGs or combinations of existing shapes

**Comment by JRegimbal** [comment]
Groupings implemented for most common neumes. Still can't display virgas for MEI 4 since it uses the `diagonalright` attribute to differentiate itself, and that's not currently in the libmei in verovio.

**Comment by JRegimbal** [comment]
Correction: `diagonalright` and other attributes are actually present in libmei but not necessarily used to render in verovio. Virgas displayed as of now.
