### ISSUE TITLE
Implement Syllable Text

### ISSUE THREAD

**Issue by ATranimal** [DDMAL/Neon2#5]
text stored in the <syl> tags should be rendered above notes

**Comment by JRegimbal** [comment]
Text present in [feature/syllable-text](https://github.com/ATranimal/verovio/commit/2f9707c8777d295b97b09e50247be6219446d4e4).

**Comment by JRegimbal** [comment]
We should probably handle this entirely in Neon. Being able to tell verovio what to render sounds like a use case unique to us. Maybe before rendering the SVG we can filter out the syllable text using d3?

**Comment by JRegimbal** [comment]
I have something that does this in the [`feature/optional-text`](https://github.com/DDMAL/Neon2/tree/feature/optional-text) branch. The version of verovio-toolkit needs to be updated before merging into `develop` but for that I'm waiting to see if Laurent wants any changes with how we're getting nc info.
