### ISSUE TITLE
make cursor images variable with scale

### ISSUE THREAD

**Issue by zoemcl** [DDMAL/Neon2#52]
Currently the cursor images for various elements are set at a static size. They should change size based on the current scale of the image.

Similarly, the slider for inserting systems should dynamically change the size of the system the user wishes to insert.

**Comment by zoemcl** [comment]
In order for this to happen, the cursor images should be rendered as svg's by verovio and follow the cursor.

**Comment by JRegimbal** [comment]
There have been no requests to go from crosshair to the actual image, so the crosshair seems to be okay as a permanent solution. Closing.
