### ISSUE TITLE
Multiple note selection

### ISSUE THREAD

**Issue by ATranimal** [DDMAL/Neon2#8]
Some sort of selection box / shift-click feature could be implemented to move multiple neumes at once

**Comment by zoemcl** [comment]
Currently functional but will need to be reworked significantly once we refactor all the neon listeners and the dragging functionality. Also, we are currently selecting by "nc" but the selection should round up or round down to the nearest neume parent depending on if the user is currently selecting by "nc" or "neume".

**Comment by zoemcl** [comment]
Change it so that upon selection the elements are added to the "selected" class instead of being given the "selected=true" attribute. This will correspond to how we are implementing single note selection.

**Comment by zoemcl** [comment]
Needs to be adapted to incorporate clefs and custos. Also, it currently only works if the user selects from left to right and not when selecting from right to left.

**Comment by zoemcl** [comment]
Working version currently in feature/select-by

**Comment by zoemcl** [comment]
feature/select-by merged to develop
