### ISSUE TITLE
Undo

### ISSUE THREAD

**Issue by zoemcl** [DDMAL/Neon2#85]
User should be able to undo actions.

**Comment by JRegimbal** [comment]
What kind of actions are we considering undoable? Just ones that make calls to verovio and change the resulting MEI? Changes to the view (zoom, panning)?

**Comment by zoemcl** [comment]
I don't think we need to be able to undo any type of display controls (zoom/opcacity/syllable text). We can limit it to actions that make or will make calls to verovio: dragging, inserting, grouping, merging systems and changing attributes.

**Comment by JRegimbal** [comment]
Undo/redo functionality added to develop in #91. Will close the issue once we add undo/redo buttons.
