### ISSUE TITLE
Syllables stay highlighted in "Syllables on this page" section

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#998]
Clicking on any neume/syllable/bounding box on a Neon page highlights the corresponding syllable in the "Syllables on this page" section. If you click on any other element, a new syllable becomes highlighted. However, at the moment, every syllable stays highlighted until you actually change something. Demonstration:

https://user-images.githubusercontent.com/83373378/233341946-110824ee-c552-4ebb-96c5-97b651761a5f.mov

To reproduce this, you can:
- Click on any number of bounding boxes, consecutive or not;
- Move between bounding boxes using the arrow keys;
- Click on any neume or neume component, consecutive or not;
- Click on any syllable, consecutive or not;
- Do any combination of the above.

To make the highlighting stop, all you have to do is make any edit, to any neume or syllable.

Again, this is not at all a work-stopping bug, but it's much clearer when only the syllable of the currently selected element on the page is highlighted.

This started happening sometime between the 14th and the 20th of April.

**Comment by yinanazhou** [comment]
Sorry @JoyfulGen, it must be the new changes I made. I will fix it ASAP.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've pushed the changes for this issue.

**Comment by JoyfulGen** [comment]
Fixed! Closing issue now.
